spring:
  datasource:
    name: testdb
    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    generate-ddl: true